[project]
name = "gpt-images"
version = "0.1.0"
description = "Combine multiple graphql-based or function-based agents with dynamic routing - based on atomic-agents."
readme = "README.md"
requires-python = "~=3.11.0"
license = "MIT"
authors = [{ name = "Sean Ryan", email = "mr.sean.ryan@gmail.com" }]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["genai", "image-generation", "image-generator-using-openai-api", "genai", "image-generation-ai", "python", "ai", "artificial-intelligence", "openai", "openai-api", "large-language-models", "llm", "large-language-model"]
dependencies = [
    "openai>=2.8.0,<3.0.0",
    "cornsnake>=0.1.1,<0.2.0",
    "torch==2.5.1+cu121",
    "torchvision==0.20.1+cu121",
    "torchaudio==2.5.1+cu121",
    "requests>=2.32.5",
    "diffusers>=0.37.0,<0.38.0",
    "transformers>=5.3.0,<6.0.0",
    "accelerate>=1.13.0,<2.0.0",
    "safetensors>=0.7.0,<0.8.0",
    "sentencepiece>=0.2.1,<0.3.0",
    "huggingface-hub>=1.7.2",
]

[project.urls]
Homepage = "https://github.com/mrseanryan/gpt-images"
Repository = "https://github.com/mrseanryan/gpt-images"
Documentation = "https://github.com/mrseanryan/gpt-images"

[dependency-groups]
dev = [
    "mypy>=1.14.0,<2.0.0",
    "ruff>=0.14.5,<0.15.0",
]
test = [
    "parameterized~=0.9.0",
]

[tool.uv]
package = false

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu121"

[[tool.uv.index]]
url = "https://pypi.org/simple"

[tool.ruff.format]
exclude = []

[tool.mypy]
check_untyped_defs = true
disallow_untyped_defs = true
disallow_any_unimported = false
ignore_missing_imports = true
warn_return_any = true
warn_unused_ignores = true
